server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://address:port/apit_server?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=GMT&jdbcCompliantTruncation=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update