server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://apit_mysql_prod:3306/apit_server?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=GMT&jdbcCompliantTruncation=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update